const form=document.getElementById('transactionForm'), typeEl=document.getElementById('type'), categoryEl=document.getElementById('category'), dateEl=document.getElementById('date'), amountEl=document.getElementById('amount'), descEl=document.getElementById('description'), editId=document.getElementById('editId'), msg=document.getElementById('formMessage');
function loadForm(){fillCategories(categoryEl);dateEl.value=today()}
function renderRows(){let tx=getTransactions();const q=document.getElementById('search').value.toLowerCase();const ft=document.getElementById('filterType').value;tx=tx.filter(x=>(!q||`${x.description} ${x.category}`.toLowerCase().includes(q))&&(ft==='all'||x.type===ft)).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('transactionRows').innerHTML=tx.map(x=>`<tr><td>${x.date}</td><td>${escapeHtml(x.description)}</td><td>${escapeHtml(x.category)}</td><td class="${x.type}">${x.type}</td><td class="${x.type}">${x.type==='income'?'+':'-'}${money(x.amount)}</td><td><button class="action-btn" onclick="editTx('${x.id}')">Edit</button><button class="action-btn delete" onclick="deleteTx('${x.id}')">Delete</button></td></tr>`).join('');document.getElementById('tableEmpty').classList.toggle('hidden',tx.length>0)}
function editTx(id){const x=getTransactions().find(t=>t.id===id);if(!x)return;editId.value=x.id;typeEl.value=x.type;fillCategories(categoryEl);categoryEl.value=x.category;dateEl.value=x.date;amountEl.value=x.amount;descEl.value=x.description;document.getElementById('formTitle').textContent='Edit Transaction';document.getElementById('cancelEdit').classList.remove('hidden');location.hash='add'}
function deleteTx(id){if(!confirm('Delete this transaction?'))return;saveTransactions(getTransactions().filter(x=>x.id!==id));renderRows()}
form.addEventListener('submit',e=>{e.preventDefault();const tx=getTransactions();const item={id:editId.value||crypto.randomUUID(),type:typeEl.value,amount:Number(amountEl.value),category:categoryEl.value,date:dateEl.value,description:descEl.value.trim()};if(!item.amount||item.amount<=0||!item.description){msg.textContent='Please enter valid transaction details.';return}const idx=tx.findIndex(x=>x.id===item.id);if(idx>=0)tx[idx]=item;else tx.push(item);saveTransactions(tx);msg.textContent='Transaction saved successfully.';form.reset();editId.value='';dateEl.value=today();document.getElementById('formTitle').textContent='Add Transaction';document.getElementById('cancelEdit').classList.add('hidden');renderRows()});
document.getElementById('cancelEdit').onclick=()=>{form.reset();editId.value='';dateEl.value=today();document.getElementById('formTitle').textContent='Add Transaction';document.getElementById('cancelEdit').classList.add('hidden')};
document.getElementById('search').oninput=renderRows;document.getElementById('filterType').onchange=renderRows;document.addEventListener('DOMContentLoaded',()=>{loadForm();renderRows()});
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
